package com.joker.storage.core;

import com.joker.storage.core.statement.FKPreparedStatement;
import com.joker.storage.core.statement.FKStatement;

import java.sql.*;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;

public class FKConnection implements Connection {
    private Session session;

    public FKConnection(Session session) {
        this.session = session;
        this.session.setConnection(this);
    }


    @Override
    public Statement createStatement() throws SQLException { return new FKStatement(session); }
    @Override
    public PreparedStatement prepareStatement(String sql) throws SQLException { return prepareStatement(sql, Statement.NO_GENERATED_KEYS); }
    @Override
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException { return new FKPreparedStatement(sql, session); }
    @Override
    public void setAutoCommit(boolean autoCommit) throws SQLException { session.setAutoCommit(autoCommit); }
    @Override
    public boolean getAutoCommit() throws SQLException { return session.autoCommit(); }
    @Override
    public void commit() throws SQLException { session.commit(); }
    @Override
    public void rollback() throws SQLException { session.rollback(); }
    @Override
    public void close() throws SQLException { session.close(); }
    @Override
    public boolean isClosed() throws SQLException { return session.isClosed(); }

    public Session getSession() { return session; }

        /******* unsupported *********/
    @Override
    public DatabaseMetaData getMetaData() throws SQLException { throw new SQLException("not support"); }

    @Override
    public CallableStatement prepareCall(String sql) throws SQLException {throw new SQLException("not support");}
    @Override
    public String nativeSQL(String sql) throws SQLException {throw new SQLException("not support");}
    @Override
    public void setReadOnly(boolean readOnly) throws SQLException {throw new SQLException("not support");}
    @Override
    public boolean isReadOnly() throws SQLException {throw new SQLException("not support");}
    @Override
    public void setCatalog(String catalog) throws SQLException {throw new SQLException("not support");}
    @Override
    public String getCatalog() throws SQLException {throw new SQLException("not support");}
    @Override
    public void setTransactionIsolation(int level) throws SQLException {throw new SQLException("not support");}
    @Override
    public int getTransactionIsolation() throws SQLException {throw new SQLException("not support");}
    @Override
    public SQLWarning getWarnings() throws SQLException {throw new SQLException("not support");}
    @Override
    public void clearWarnings() throws SQLException {throw new SQLException("not support");}
    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {throw new SQLException("not support");}
    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {throw new SQLException("not support");}
    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {throw new SQLException("not support");}
    @Override
    public Map<String, Class<?>> getTypeMap() throws SQLException {throw new SQLException("not support");}
    @Override
    public void setTypeMap(Map<String, Class<?>> map) throws SQLException {throw new SQLException("not support");}
    @Override
    public void setHoldability(int holdability) throws SQLException {throw new SQLException("not support");}
    @Override
    public int getHoldability() throws SQLException {throw new SQLException("not support");}
    @Override
    public Savepoint setSavepoint() throws SQLException {throw new SQLException("not support");}
    @Override
    public Savepoint setSavepoint(String name) throws SQLException {throw new SQLException("not support");}
    @Override
    public void rollback(Savepoint savepoint) throws SQLException {throw new SQLException("not support");}
    @Override
    public void releaseSavepoint(Savepoint savepoint) throws SQLException {throw new SQLException("not support");}
    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {throw new SQLException("not support");}
    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {throw new SQLException("not support");}
    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {throw new SQLException("not support");}
    @Override
    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {throw new SQLException("not support");}
    @Override
    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {throw new SQLException("not support");}
    @Override
    public Clob createClob() throws SQLException {throw new SQLException("not support");}
    @Override
    public Blob createBlob() throws SQLException {throw new SQLException("not support");}
    @Override
    public NClob createNClob() throws SQLException {throw new SQLException("not support");}
    @Override
    public SQLXML createSQLXML() throws SQLException {throw new SQLException("not support");}
    @Override
    public boolean isValid(int timeout) throws SQLException {throw new SQLException("not support");}
    @Override
    public void setClientInfo(String name, String value) throws SQLClientInfoException {throw new SQLClientInfoException();}
    @Override
    public void setClientInfo(Properties properties) throws SQLClientInfoException {throw new SQLClientInfoException();}
    @Override
    public String getClientInfo(String name) throws SQLException {throw new SQLException("not support");}
    @Override
    public Properties getClientInfo() throws SQLException {throw new SQLException("not support");}
    @Override
    public Array createArrayOf(String typeName, Object[] elements) throws SQLException {throw new SQLException("not support");}
    @Override
    public Struct createStruct(String typeName, Object[] attributes) throws SQLException {throw new SQLException("not support");}
    @Override
    public void setSchema(String schema) throws SQLException {throw new SQLException("not support");}
    @Override
    public String getSchema() throws SQLException {throw new SQLException("not support");}
    @Override
    public void abort(Executor executor) throws SQLException {throw new SQLException("not support");}
    @Override
    public void setNetworkTimeout(Executor executor, int milliseconds) throws SQLException {throw new SQLException("not support");}
    @Override
    public int getNetworkTimeout() throws SQLException {throw new SQLException("not support");}
    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException {throw new SQLException("not support");}
    @Override
    public boolean isWrapperFor(Class<?> iface) throws SQLException {throw new SQLException("not support");}
}
